title: Ha Rim Jung
description: Quantitative Researcher | Sogang University
url: "https://gkfla2020-bit.github.io"
baseurl: ""

# GitHub Pages 기본 테마
theme: jekyll-theme-minimal

# 저자 정보
author: Ha Rim Jung

# 마크다운
markdown: kramdown
highlighter: rouge

# 기본값
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

include:
  - _pages

# 플러그인
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
